/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "dsvm.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_Torque_Level(void);
extern void test_Sector_Calc_Low_Speed(void);
extern void test_Sector_Calc_Med_Speed(void);
extern void test_Sector_Calc_High_Speed(void);
extern void test_Speed_Region(void);


/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/TestDsvm.c");
  RUN_TEST(test_Torque_Level, 17);
  RUN_TEST(test_Sector_Calc_Low_Speed, 29);
  RUN_TEST(test_Sector_Calc_Med_Speed, 50);
  RUN_TEST(test_Sector_Calc_High_Speed, 71);
  RUN_TEST(test_Speed_Region, 92);

  return (UnityEnd());
}
